# Generated by Django 6.0.7 on 2026-08-05 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('department', models.CharField(default='Computer Science', max_length=100)),
                ('year', models.CharField(default='1st Year', max_length=20)),
                ('section', models.CharField(default='A', max_length=10)),
                ('mathematics', models.FloatField(default=0.0)),
                ('physics', models.FloatField(default=0.0)),
                ('programming', models.FloatField(default=0.0)),
                ('database_management', models.FloatField(default=0.0)),
                ('operating_systems', models.FloatField(default=0.0)),
                ('learning_preference', models.CharField(choices=[('Practical', 'Practical'), ('Theory', 'Theory'), ('Mixed', 'Mixed')], default='Mixed', max_length=20)),
                ('availability', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], default='Morning', max_length=20)),
                ('average_score', models.FloatField(default=0.0)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_assignments', to='groups.studygroup')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
