# Generated by Django 5.2.17 on 2026-08-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_studygroup_group_created_idx_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['email'], name='student_email_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['department'], name='student_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['average_score'], name='student_avg_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['created_at'], name='student_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(condition=models.Q(('database_management__gte', 0.0), ('database_management__lte', 100.0), ('mathematics__gte', 0.0), ('mathematics__lte', 100.0), ('operating_systems__gte', 0.0), ('operating_systems__lte', 100.0), ('physics__gte', 0.0), ('physics__lte', 100.0), ('programming__gte', 0.0), ('programming__lte', 100.0)), name='student_scores_range_0_100'),
        ),
    ]
