# Generated by Django 6.0.7 on 2026-08-05 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('group_generated', 'Group generated'), ('csv_imported', 'CSV imported'), ('report_exported', 'Report exported'), ('student_registered', 'Student registered'), ('student_updated', 'Student updated'), ('group_deleted', 'Group deleted'), ('duplicate_skipped', 'Duplicate skipped'), ('student_deleted', 'Student deleted'), ('profile_updated', 'Profile updated'), ('settings_updated', 'Settings updated')], max_length=40)),
                ('actor', models.CharField(default='admin', max_length=40)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('student', 'student')], max_length=10)),
                ('category', models.CharField(default='system', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('tone', models.CharField(choices=[('success', 'success'), ('warning', 'warning'), ('info', 'info')], default='info', max_length=10)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
