# Generated by Django 5.2.17 on 2026-08-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('students', '0002_student_student_email_idx_student_student_dept_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', 'created_at'], name='activity_action_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['role', 'read'], name='notif_role_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notif_created_idx'),
        ),
    ]
