# Generated by Django 6.0.7 on 2026-08-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members', models.JSONField(default=list)),
                ('overall_strengths', models.JSONField(default=list)),
                ('overall_weaknesses', models.JSONField(default=list)),
                ('average_performance', models.FloatField(default=0.0)),
                ('complementary_skill_score', models.FloatField(default=0.0)),
                ('team_leader', models.CharField(blank=True, max_length=255)),
                ('learning_recommendation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
