# Generated by Django 6.0.7 on 2026-08-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='recommendations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
