# Generated by Django 5.2.17 on 2026-08-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_studygroup_recommendations'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['created_at'], name='group_created_idx'),
        ),
        migrations.AddIndex(
            model_name='studygroup',
            index=models.Index(fields=['average_performance'], name='group_perf_idx'),
        ),
    ]
