# Generated by Django 5.2.17 on 2026-08-13 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_studygroup_group_created_idx_and_more'),
        ('students', '0002_student_student_email_idx_student_student_dept_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='groups.studygroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='students.student')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['group', 'created_at'], name='chat_group_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='SharedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('Study Notes', 'Study Notes'), ('Documents', 'Documents'), ('Useful Links', 'Useful Links'), ('Videos', 'Videos'), ('Assignments', 'Assignments'), ('Other', 'Other')], default='Other', max_length=20)),
                ('url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='groups.studygroup')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_resources', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['group', 'created_at'], name='resource_group_created_idx')],
            },
        ),
    ]
