# Generated by Django 6.0.7 on 2026-08-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departments', models.JSONField(default=list)),
                ('default_group_size', models.IntegerField(default=4)),
                ('kmeans_random_state', models.IntegerField(default=42)),
                ('kmeans_max_iterations', models.IntegerField(default=300)),
                ('export_default_format', models.CharField(default='csv', max_length=10)),
                ('notify_groups_generated', models.BooleanField(default=True)),
                ('notify_csv_imported', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System settings',
            },
        ),
    ]
